---
title: "Materials"
output: html_document

---

### To do before workshop (in this order!):

1. [Download R](https://www.r-project.org).

2. [Download RStudio](https://www.rstudio.com/products/rstudio/download/)

3. [Download .R script](https://scholarship.miami.edu/esploro/outputs/dataset/Data-for-Interannual-variability-in-the/991031652420702976) to run mixing model. Scroll down to "Files and links" and click "Download." Unzip file and save to your local computer. The folder is called "Gaston_2022_update".

4. Open RStudio. Open the file "mixingmodel.R" in the Gaston_2022_update folder in RStudio.

5. Follow the directions in mixingmodel.R file and install the packages "MixSIAR", "ggplot2", "MCMCpack", "rjags" and "R2jags" starting on line 14 (shown below).

````
#Install the package "MixSIAR", "ggplot2", and "rjags" by running lines 14, 15, and 16. 
install.packages("MixSIAR")
install.packages("ggplot2")
install.packages("MCMCpack")
install.packages("rjags")
# NOTE: the rjags library requires that "jags" is installed on the system
# https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/
install.packages("R2jags")

````
6. Download the [MixSIAR User Manual](https://zenodo.org/record/47719#.YzcQtS-z10s)

You're ready for the workshop!


Unable to download R or RStudio? Unable to download the packages? No problem, we'd love to see you at the workshop anyways and are here to help!

### Other materials

##### From the creator of MixSIAR, Brian Stock of Scripps


1. [Website](https://brianstock.github.io/mixsiar/#:~:text=MixSIAR%20is%20an%20open-source,following%20the%20MixSIAR%20model%20framework.)

2. [Stock et al. 2018](https://peerj.com/articles/5096/) 

##### Other papers using MixSIAR

1. [Anne's 2022](https://agupubs.onlinelibrary.wiley.com/doi/10.1029/2021GL097344) paper using MixSIAR using Sr, Nd, and Pb isotopes

2. Jack Longman's 2018 paper (optimizing MixSIAR to use with Pb isotopes): https://www.nature.com/articles/s41598-018-24474-0

##### Resources to help understand Mixing Models/MixSIAR

1. A simple introduction to Markov-Chain Monte Carlo sampling: https://link.springer.com/article/10.3758/s13423-016-1015-8
 
